# Site settings
title: DSIO Håndbold
email: mail@dsiohaandbold.dk
description: "DSIO Håndbold er en håndboldklub for studerende og andre ligesindede i Odense."
baseurl: ""
url: "http://localhost:4000"
encoding: utf-8
timezone: Europe/Copenhagen

# Build settings
exclude:
- Gemfile
- Gemfile.lock
- Gruntfile.js
- node_modules
- package.json
markdown: kramdown
permalink: pretty

sass:
    style: :compressed

collections:
    hold:
        output: true
