# Site settings
title: DSIO Håndbold
email: mail@dsiohaandbold.dk
description: "DSIO Håndbold er en håndboldklub for studerende og andre ligesindede i Odense."
baseurl: ""
url: "http://localhost:4000"

# Build settings
markdown: kramdown
permalink: pretty

collections:
    hold:
        output: true
    stillinger:
        output: false
    kampe:
        output: false
    personer:
        output: false