# Site settings
title: DSIO Håndbold
email: mail@dsiohaandbold.dk
description: "DSIO Håndbold er en håndboldklub for studerende og andre ligesindede i Odense."
baseurl: ""
url: "http://localhost:4000"
encoding: utf-8
timezone: Europe/Copenhagen

# Build settings
exclude:
- Gemfile
- Gemfile.lock
- Gruntfile.js
- node_modules
- package.json
- Readme.md
markdown: kramdown
permalink: pretty

sass:
    style: :compressed

collections:
    hold:
        output: true

menu:
- name: Klubben
  parent: main
  position: 1
- name: Hold
  parent: main
  position: 2
- name: Sponsorer
  parent: main
  position: 5
